[package]
name = "relos-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
relos-core = { path = "../relos-core" }
relos-store = { path = "../relos-store" }
relos-log = { path = "../relos-log" }
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
bincode.workspace = true
